//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesAndTechnicalService.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Db_TechnicalServiceEntities : DbContext
    {
        public Db_TechnicalServiceEntities()
            : base("name=Db_TechnicalServiceEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TblAdmin> TblAdmins { get; set; }
        public virtual DbSet<TblCathegory> TblCathegories { get; set; }
        public virtual DbSet<TblCost> TblCosts { get; set; }
        public virtual DbSet<TblCurrent> TblCurrents { get; set; }
        public virtual DbSet<TblDefectiveProduct> TblDefectiveProducts { get; set; }
        public virtual DbSet<TblDepartment> TblDepartments { get; set; }
        public virtual DbSet<TblEmployee> TblEmployees { get; set; }
        public virtual DbSet<TblInvoiceBas> TblInvoiceBases { get; set; }
        public virtual DbSet<TblInvoiceDetail> TblInvoiceDetails { get; set; }
        public virtual DbSet<TblNote> TblNotes { get; set; }
        public virtual DbSet<TblProcess> TblProcesses { get; set; }
        public virtual DbSet<TblProdcutTracking> TblProdcutTrackings { get; set; }
        public virtual DbSet<TblProductAcceptance> TblProductAcceptances { get; set; }
        public virtual DbSet<TblProduct> TblProducts { get; set; }
        public virtual DbSet<TblSale> TblSales { get; set; }
        public virtual DbSet<Tbl_Cities> Tbl_Cities { get; set; }
        public virtual DbSet<Tbl_Countries> Tbl_Countries { get; set; }
        public virtual DbSet<Tbl_Provinces> Tbl_Provinces { get; set; }
        public virtual DbSet<TBl_Contact> TBl_Contact { get; set; }
        public virtual DbSet<TblAbout> TblAbouts { get; set; }
    
        public virtual ObjectResult<listcatpro_Result> listcatpro()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<listcatpro_Result>("listcatpro");
        }
    
        public virtual ObjectResult<listcatpro1_Result> listcatpro1()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<listcatpro1_Result>("listcatpro1");
        }
    }
}
