//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesAndTechnicalService.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblCurrent
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblCurrent()
        {
            this.TblInvoiceBases = new HashSet<TblInvoiceBas>();
            this.TblProductAcceptances = new HashSet<TblProductAcceptance>();
            this.TblSales = new HashSet<TblSale>();
        }
    
        public int CurrentId { get; set; }
        public string CurrentName { get; set; }
        public string CurrentSurname { get; set; }
        public string CurrentPhone { get; set; }
        public string CurrentMail { get; set; }
        public string CurrentCountry { get; set; }
        public string CurrentCity { get; set; }
        public string CurrentProvince { get; set; }
        public string CurrentBank { get; set; }
        public string CurrentTaxOffice { get; set; }
        public string CurrentTaxNumber { get; set; }
        public string CurrentStatus { get; set; }
        public string CurrentAddress { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblInvoiceBas> TblInvoiceBases { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblProductAcceptance> TblProductAcceptances { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblSale> TblSales { get; set; }
    }
}
