//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesAndTechnicalService.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblCost
    {
        public int CostId { get; set; }
        public string CostTitle { get; set; }
        public string CostDate { get; set; }
        public Nullable<decimal> CostAmount { get; set; }
    }
}
