//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesAndTechnicalService.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblInvoiceBas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblInvoiceBas()
        {
            this.TblInvoiceDetails = new HashSet<TblInvoiceDetail>();
        }
    
        public int InvoiceBaseId { get; set; }
        public string InvoiceBaseSerie { get; set; }
        public string InvoiceBaseOrderNo { get; set; }
        public string InvoiceBaseDate { get; set; }
        public string InvoiceBaseHour { get; set; }
        public string InvoiceBaseTaxOffice { get; set; }
        public Nullable<int> InvoiceBaseCurrentId { get; set; }
        public Nullable<int> InvoiceBaseEmployee { get; set; }
    
        public virtual TblCurrent TblCurrent { get; set; }
        public virtual TblEmployee TblEmployee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblInvoiceDetail> TblInvoiceDetails { get; set; }
    }
}
