//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesAndTechnicalService.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblInvoiceDetail
    {
        public int InvoiceDetailsId { get; set; }
        public string InvoiceDetailsProduct { get; set; }
        public Nullable<short> InvoiceDetailsPiece { get; set; }
        public Nullable<decimal> InvoiceDetailsPrice { get; set; }
        public Nullable<decimal> InvoiceDetailsTotalPrice { get; set; }
        public Nullable<int> InvoiceId { get; set; }
    
        public virtual TblInvoiceBas TblInvoiceBas { get; set; }
    }
}
