//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesAndTechnicalService.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblNote
    {
        public int NoteId { get; set; }
        public string NoteTitle { get; set; }
        public string NoteContext { get; set; }
        public Nullable<bool> NoteStatus { get; set; }
    }
}
