//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesAndTechnicalService.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblProductAcceptance
    {
        public int AcceptId { get; set; }
        public Nullable<int> AcceptEmployee { get; set; }
        public Nullable<int> AcceptCurrentId { get; set; }
        public string AcceptComingDate { get; set; }
        public string AcceptGointDate { get; set; }
        public string AcceptSerieNo { get; set; }
    
        public virtual TblCurrent TblCurrent { get; set; }
        public virtual TblEmployee TblEmployee { get; set; }
    }
}
