//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesAndTechnicalService.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblSale
    {
        public int SaleId { get; set; }
        public Nullable<int> SaleProduct { get; set; }
        public Nullable<int> SaleCustomer { get; set; }
        public Nullable<int> SaleEmployee { get; set; }
        public string SaleDate { get; set; }
        public Nullable<short> SalePiece { get; set; }
        public Nullable<decimal> SalePrice { get; set; }
        public Nullable<decimal> SaleTotalPrice { get; set; }
        public string SaleProdutSerieNo { get; set; }
    
        public virtual TblCurrent TblCurrent { get; set; }
        public virtual TblEmployee TblEmployee { get; set; }
        public virtual TblProduct TblProduct { get; set; }
    }
}
